### ISSUE TITLE
Import selected PRs from SingularityCE 4.1.x

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#2126]
Add `--authfile` option:
- [x] sylabs/singularity#2227
- [x] sylabs/singularity#2225
- [x] sylabs/singularity#2236
- [x] sylabs/singularity#2238

Refactor to use go-container registry:
- [x] sylabs/singularity#2376
- [x] sylabs/singularity#2379
- [x] sylabs/singularity#2407
- [x] sylabs/singularity#2390

Miscellaneous:
- [x] sylabs/singularity#2230
- [ ] (not needed) sylabs/singularity#2329
- [x] sylabs/singularity#2374
- [x] sylabs/singularity#2380
- [x] sylabs/singularity#2408
- [ ] (not needed) Consider the host cleanup commit from sylabs/singularity#2451

Fixes backported to 4.1 branch:
- [x] sylabs/singularity#2569
- [ ] (not needed) sylabs/singularity#2573
- [ ] (not needed) sylabs/singularity#2699
- [x] sylabs/singularity#2777

Lint:
- [ ] (not needed) sylabs/singularity#2281
- [x] sylabs/singularity#2373
- [x] sylabs/singularity#2409

**Comment by DrDaveD** [comment]
@JasonYangShadow why don't you figure on working on the first two batches having to do with `--authfile` and the go-containerregistry refactor and I'll figure on doing at least some of the miscellaneous.  We'll see how things go after those are done.

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow why don't you figure on working on the first two batches having to do with `--authfile` and the go-containerregistry refactor and I'll figure on doing at least some of the miscellaneous. We'll see how things go after those are done.

Sure, no problem!

**Comment by DrDaveD** [comment]
@JasonYangShadow great job on finishing the first two batches.  Please move on next to the backported fixes.  I should to be able to start to do some of the miscellaneous ones next week.
