### ISSUE TITLE
Import selected PRs from SingularityCE 4.2.x

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#2546]
### Cleanup

- [x] sylabs/singularity#2919
- [x] sylabs/singularity#2957

### Testing

- [x] sylabs/singularity#2984
- [x] sylabs/singularity#2989
- [x] sylabs/singularity#2990
- [x] sylabs/singularity#2991
- [x] sylabs/singularity#3107

### New configuration options

- [x] sylabs/singularity#2915
- [x] sylabs/singularity#2956
- [x] sylabs/singularity#2981

### Miscellaneous

- [x] sylabs/singularity#2789
- [x] sylabs/singularity#2855
- [x] sylabs/singularity#2924
- [x] sylabs/singularity#3192 (at least the corrections to apptainer.conf, consider the new feature)
- [x] sylabs/singularity#3225 (selected commits)
- [x] sylabs/singularity#3266

### Lint

- [x] sylabs/singularity#3222 (just the "nolint lint" commit, and I think only one applies) - Skip because removing the `//nolint:gosec tags causes gosec ilnt errors.

**Comment by JasonYangShadow** [comment]
@DrDaveD 

https://github.com/sylabs/singularity/pull/3225

regarding the cherry-pick of the above PR, Apptainer uses https://pkg.go.dev/github.com/apptainer/sif/v2 rather than https://pkg.go.dev/github.com/sylabs/sif/v2 which has version `2.19.0`, we can not cherry-pick it.

**Comment by DrDaveD** [comment]
We need to update our sif to 2.19.2.  Can you please submit a PR there that cherry-picks everything missing, to bring it up to date?

**Comment by JasonYangShadow** [comment]
> We need to update our sif to 2.19.2. Can you please submit a PR there that cherry-picks everything missing, to bring it up to date?

https://github.com/apptainer/sif/pull/245

created one PR syncing from sylabs sif repo.
